name: depot-build-and-push

on: push

jobs:
  docker:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: depot/build-push-action@v1
        with:
          project: b4qlt63xvg
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            reclaimthestack/rails-example:latest
            reclaimthestack/rails-example:sha-${{ github.sha }}
